version: "3.8"

services:
  web:
    container_name: web
#    restart: always
    build: .
    command: "sh -c 'uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload'"
    expose:
      - "8000"
    volumes:
      - ./:/code
      - ./static:/static
    env_file: .env
    depends_on:
      - redis


  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    expose:
      - "6379"
    env_file: .env


  celery:
    container_name: celery
    build: .
#    restart: always
    command: "celery -A app.worker worker -l info -Q main-queue -c 2"
    volumes:
      - ./:/code
      - ./static:/static
    depends_on:
      - web
      - redis
    env_file: .env


  caddy:
    image: caddy:alpine
    container_name: caddy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./static:/srv
