version: "3.8"

x-common: &common
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - ./:/code
    - ./static:/static
  env_file: .env

services:
  web:
    <<: *common
    container_name: web
    command: "sh -c 'uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload'"
    expose:
      - "8000"
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    expose:
      - "6379"
    env_file: .env

  celery:
    <<: *common
    container_name: celery
    command: "celery -A app.worker worker -l info -Q main-queue -c 2"
    depends_on:
      - web
      - redis

  caddy:
    image: caddy:alpine
    container_name: caddy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./static:/srv
